### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by mchojrincodurance** [texttest/TextTestJetBrainsPlugin#1]
Hi:

  I downloaded the code and try to build the plugin using `./gradlew buildPlugin` and got this error:

```
> Task :buildSearchableOptions
2023-06-07 11:37:34,663 [   2407] SEVERE - #c.i.i.p.PluginManager - Current thread: Thread[AWT-EventQueue-1,6,main]; expected: Thread[AWT-EventQueue-0,6,]
java.lang.IllegalStateException: Current thread: Thread[AWT-EventQueue-1,6,main]; expected: Thread[AWT-EventQueue-0,6,]
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.checkWriteThreadAccess(ReadMostlyRWLock.java:287)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeIntentLock(ReadMostlyRWLock.java:196)
        at com.intellij.openapi.application.impl.ApplicationImpl.acquireWriteIntentLock(ApplicationImpl.java:944)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$new$2(ApplicationImpl.java:181)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-06-07 11:37:34,666 [   2410] SEVERE - #c.i.i.p.PluginManager - IntelliJ IDEA 2022.1.4  Build #IC-221.6008.13
2023-06-07 11:37:34,670 [   2414] SEVERE - #c.i.i.p.PluginManager - JDK: 11.0.15; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-06-07 11:37:34,670 [   2414] SEVERE - #c.i.i.p.PluginManager - OS: Linux

Start Failed
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.IllegalStateException: Current thread: Thread[AWT-EventQueue-1,6,main]; expected: Thread[AWT-EventQueue-0,6,]
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.checkWriteThreadAccess(ReadMostlyRWLock.java:287)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeIntentLock(ReadMostlyRWLock.java:196)
        at com.intellij.openapi.application.impl.ApplicationImpl.acquireWriteIntentLock(ApplicationImpl.java:944)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$new$2(ApplicationImpl.java:181)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

-----
Your JRE: 11.0.15+10-b2043.56 amd64 (JetBrains s.r.o.)
/home/mauro/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_15-linux-x64-b2043.56/extracted/jbr

> Task :buildSearchableOptions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSearchableOptions'.
> Process 'command '/home/mauro/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_15-linux-x64-b2043.56/extracted/jbr/bin/java'' finished with non-zero exit value 3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 8s
12 actionable tasks: 12 executed
```

  Then I tried `./gradlew verifyPlugin` and got this:

```
> Task :initializeIntelliJPlugin
[gradle-intellij-plugin :initializeIntelliJPlugin] Gradle IntelliJ Plugin is outdated: 1.13.2. Update `org.jetbrains.intellij` to: 1.14.1

> Task :verifyPlugin FAILED
[gradle-intellij-plugin :verifyPlugin] Plugin name specified in plugin.xml should not contain the word 'plugin'
[gradle-intellij-plugin :verifyPlugin] Invalid plugin descriptor 'description': All links in description must be HTTPS: http://texttest.org

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyPlugin'.
> Plugin verification failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
12 actionable tasks: 6 executed, 6 up-to-date
```

  Are there any specific installation instructions I might be missing? Thanks

**Comment by emilybache** [comment]
I'm really pleased you were interested enough to want to try to install this! This is the first time I tried to develop a plugin and I think I failed to set the gradle project up correctly. Sorry about that.

The plugin really doesn't have much functionality yet - you can achieve the same results with an ordinary run configuration in the IDE actually. It is supposed to launch texttest from within the IDE by executing a command line like 'texttest -con -d some/path/to/a/config/file' on linux. On Windows it's slightly different, but I hadn't got around to making the plugin support that yet. I suggest you try to set up an ordinary run configuration for the time being if you'd like to launch texttest from within your IDE. If you need some help with that, please ask on the TextTest mailing list: https://sourceforge.net/p/texttest/mailman/texttest-users/

If you're interested in contributing and improving this plugin, please let me know.

**Comment by mchojrincodurance** [comment]
Thanks! I was actually looking for a way to use code coverage together with texttest in order to validate the input set I'd use for generating a golden master and I figured this plugin could help... maybe a little too optimistic? :)

Anyway, I'll see what I can do in terms of contributing... I never created a plugin myself.

**Comment by emilybache** [comment]
Yes, I'm afraid this plugin won't help you with that. What you'll need is a commandline coverage tool that texttest can launch as a wrapper around your normal test rig. I'm not sure we have much documentation for this. If you can't work it out, you can get help on the mailing list I mentioned.

**Comment by mchojrincodurance** [comment]
Great. Thanks!!
